FROM ckan/ckan-base:2.9

# Install any extensions needed by your CKAN instance
# See Dockerfile.dev for more details and examples
### Scheming ###
RUN  pip3 install -e 'git+https://github.com/ckan/ckanext-scheming.git@master#egg=ckanext-scheming'
### Hierarchy ###
RUN  pip3 install -e 'git+https://github.com/ckan/ckanext-hierarchy.git#egg=ckanext-hierarchy'
### PDF View ###
RUN  pip3 install -e 'git+https://github.com/ckan/ckanext-pdfview.git#egg=ckanext-pdfview'
### Thai GDC ###
# RUN  pip3 install -e 'git+https://gitlab.nectec.or.th/opend/ckanext-thai_gdc.git@v2.1.0#egg=ckanext-thai_gdc'
# Copy custom initialization scripts
COPY docker-entrypoint.d/* /docker-entrypoint.d/
RUN pip install -r ${APP_DIR}/src/ckan/requirements.txt

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)
COPY patches ${APP_DIR}/patches

RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done
