name: vulnerability checker
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scan for vulnerabilities for ckan image
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ckan-docker/ckan:latest
          dockerfile: ./ckan/Dockerfile
      - name: Scan for vulnerabilities for ckan xloader image
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ckan-docker/ckan-xloader:latest
          dockerfile: ./ckan/ckanext-xloader/Dockerfile
